from abc import ABC

class SessionStorage(ABC):
    def save_session(self, session: Session) -> None: ...
    def get_session(self, session_id: str) -> Optional[Session]: ...
    def delete_session(self, session_id: str) -> None: ...
    def save_inference_config(self, session_id: str, config: InferenceConfig) -> None: ...
    def get_inference_config(self, session_id: str) -> Optional[InferenceConfig]: ...
