FROM node:22.23.1-alpine3.24 AS portal-build

WORKDIR /app/plexa_portal

COPY plexa_portal/package*.json ./
RUN npm ci

COPY plexa_portal ./

ARG VITE_APP_ENV=production
ARG VITE_API_BASE_URL=/api
ARG TARGET_API_VERSION=v1
ARG VITE_AUTH_MODE=dev
ARG VITE_ENABLE_DEV_LOGIN=false
ARG VITE_AUTH_AUTHORITY=
ARG VITE_AUTH_DISCOVERY_URL=
ARG VITE_AUTH_CLIENT_ID=
ARG VITE_AUTH_SCOPE="openid profile email"
ARG VITE_AUTH_REDIRECT_URI=
ARG VITE_AUTH_LOGOUT_REDIRECT_URI=

ENV VITE_APP_ENV=$VITE_APP_ENV
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV TARGET_API_VERSION=$TARGET_API_VERSION
ENV VITE_AUTH_MODE=$VITE_AUTH_MODE
ENV VITE_ENABLE_DEV_LOGIN=$VITE_ENABLE_DEV_LOGIN
ENV VITE_AUTH_AUTHORITY=$VITE_AUTH_AUTHORITY
ENV VITE_AUTH_DISCOVERY_URL=$VITE_AUTH_DISCOVERY_URL
ENV VITE_AUTH_CLIENT_ID=$VITE_AUTH_CLIENT_ID
ENV VITE_AUTH_SCOPE=$VITE_AUTH_SCOPE
ENV VITE_AUTH_REDIRECT_URI=$VITE_AUTH_REDIRECT_URI
ENV VITE_AUTH_LOGOUT_REDIRECT_URI=$VITE_AUTH_LOGOUT_REDIRECT_URI

RUN npm run build

FROM caddy:2.11.4-alpine

COPY deploy/Caddyfile /etc/caddy/Caddyfile
COPY --from=portal-build /app/plexa_portal/dist /srv
